name: Autism ML CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-train-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download autism dataset
      run: |
        mkdir -p data
        wget -O data/autism.csv https://media.geeksforgeeks.org/wp-content/uploads/20250402123330894287/train.csv
    - name: Train the Model
      run: |
        python model/train.py

    - name: Run Tests
      run: |
        pytest tests/

    - name: Validate Model Output
      run: |
        python tests/test_model.py
